-- 1) Which product has the highest price? Only return a single row.
-- 2)  Which customer has made the most orders?
-- 3) What's the total revenue per product?
-- 4) Find the orders and revenue trend
-- 5) Find the first order (by date) for each customer.
-- 6) Find the top 3 customers who have ordered the most distinct products
-- 7) Which product has been bought the highest & least in terms of quantity?
